### ISSUE TITLE
.NET6.0 support

### ISSUE THREAD

**Issue by ITaluone** [Codeuctivity/OpenXmlPowerTools#101]
It would be cool if you could add .NET6.0 support as well :)

I have cloned the project and switched manually to .NET6.0 and use this "custom" version, but it is pretty uncomfortable to get updates :)

Thank you! :)

**Comment by stesee** [comment]
The free maintaining of my projects is limited to current .net versions. .net 6 is fading out and I have no use of supporting it. Are you interested in funding .net 6 support?
