### ISSUE TITLE
Feasibility of enhancing this project to show a more accurate HTML rendition of a document?

### ISSUE THREAD

**Issue by catmanjan** [Codeuctivity/OpenXmlPowerTools#107]
Hello, I am just wondering on the authors position on the feasibility of enhancing this project to work more like the office web app viewer? e.g.

http://view.officeapps.live.com/op/view.aspx?src=https://calibre-ebook.com/downloads/demos/demo.docx

This retains the styling and pages of a document more accurately than the current powertools converter does.

Before I delve deeper, what do you think about the feasibility of doing this?

**Comment by stesee** [comment]
This project would require significant development effort, likely person-years, to be competitive with [Office Web Apps](http://view.officeapps.live.com/). Rendering OpenXML to HTML is a feature many projects have attempted, with varying degrees of success, though none of the successful ones are open-source. The most complete open-source solution available would be to use LibreOffice.

Depending on the specific requirements you're missing, it could still be an option to extend this project. For example, this fork of the project successfully added page breaks support in the HTML output.
