### ISSUE TITLE
"New" OpenXmlPowerTools

### ISSUE THREAD

**Issue by coinzdude** [Codeuctivity/OpenXmlPowerTools#74]
Hi, @Codeuctivity, 

This fork looks to be very active.  I have also some local fixes I have not attempted to PR back to Eric's original repo as it appears it may be end of life. I'm not certain, though.

Would you be interested in separating your fork as a new standalone repo?

**Comment by stesee** [comment]
Fixes wich are covered with tests are welcome. Don't hesitate to create a PR.
