### ISSUE TITLE
Update Dependency: Upgrade DocumentFormat.OpenXml to Version 3.0.1

### ISSUE THREAD

**Issue by NikolayIT** [Codeuctivity/OpenXmlPowerTools#96]

**Comment by stesee** [comment]
That would be great. A PR is welcome. I got not spare time for migrating that myself.  DocumentFormat.OpenXml 3.x brings some breaking changes.

**Comment by wuxiaojun514** [comment]
I created a pr #99 to upgrade to Version 3.0.2.
